#!/bin/bash
cd "${0%/*}" || exit                        # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

plotVelocity() {
	
#    timeDir=$1

    echo "    Plotting the velocity."

    #u0 = 0.2;
#    eta(r, s)=r * sqrt(u0 / (2 * 1.0e-5 * s))

    outName="1_velocity.png"
    gnuplot<<PLT_VEL
    set terminal pngcairo font "helvetica,10" size 1000, 250
    set xrange [0:6]
    set yrange [0:1.2]
    set grid
    set key bottom left
    set key samplen 2
    set key spacing 1
    set xlabel '{/Symbol h}'
    set ylabel "u/U"
    set offset .05, .05
    set output "$outName"
    set title "Velocity"


    bench = "../BlasiusSolution.dat"
    input1 = "blasiusFoam/postProcessing/sampleDict/500/x+0.05_T_u.xy"
    input2 = "mySimpleFoam/postProcessing/sampleDict/500/x+0.05_U.xy"



plot \                                                      
    input1 u (($1*sqrt(0.2/(2*1.0e-5*0.005))):($3/u0) t "blasius_x=0.005" w l lw 2 lc rgb "#009E73", \          
    input2 u (($1*sqrt(0.2/2*1.0e-5*0.005))):($2/u0) t "simpleFoam" w l lw 2 lc rgb "#0072B2", \          
    bench every ::5 u 1:2 t "BenchMark" w l lw 2 dt 2 lc rgb "#D55E00"  
PLT_VEL
}

#------------------------------------------------------------------------------

# Require gnuplot
command -v gnuplot >/dev/null || {
    echo "gnuplot not found - skipping graph creation" 1>&2
    exit 1
}


#timeDir=$(foamListTimes -case $models -latestTime)

#models=('blasiusFoam' 'mySimpleFoam')
#
#
#timeDir=()
#n=0
#cfDir=()
#cfUDir=()
#sepDir=()
#
#for model in "${models[@]}"
#do 
#	currentTimeDir=$(foamListTimes -case ${model} -latestTime)
#	timeDir[$n]="${model}/postProcessing/sampleDict/$currentTimeDir"
##	cfDir[$n]="${model}/postProcessing/sampleLowerPatch/surface/$currentTimeDir"
##	cfUDir[$n]="${model}/postProcessing/sampleUpperPatch/surface/$currentTimeDir"
##	sepDir[$n]="${model}/postProcessing/surfaces/$currentTimeDir"
#	n=$(($n+1))
#done
#
#echo "All time directories:${timeDir[@]}"

#plotVelocity timeDir[@] models[@]
#plotVelocity "$timeDir"
plotVelocity 



#------------------------------------------------------------------------------
